"""add applications phone\is_coppleted

Revision ID: 2a4dd406ac22
Revises: dd628b3c125c
Create Date: 2025-01-10 15:07:31.570829

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2a4dd406ac22'
down_revision: Union[str, None] = 'dd628b3c125c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('applications', sa.Column('phone_number', sa.String(length=20), nullable=True))
    op.add_column('applications', sa.Column('is_completed', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('applications', 'is_completed')
    op.drop_column('applications', 'phone_number')
    # ### end Alembic commands ###
